#!/bin/bash
set -e
ptctools="./../../python/ptctools/ptctools.py"

if [[ $# < 1 ]]; then
	echo "Usage: build ASMSOURCE asmloader.txt ASMLOADERNAME program.txt PROGRAMNAME"
	exit
fi

arm-none-eabi-as $1 -o out.elf
arm-none-eabi-objcopy -O binary out.elf out.bin

rm out.elf

if [[ $# < 2 ]]; then
	echo "Provide names to continue"
	exit
fi

$ptctools encode $2 --name $3
$ptctools encode $4 --name $5
$ptctools encode out.bin --format GRP --name TEMPGRP0

$ptctools pack $3.PTC -s 0x40000 --data-files TEMPGRP0.PTC
$ptctools qr $3.PTC --merge
$ptctools qr $5.PTC --merge

eog $3#merged.png $5#merged.png

rm TEMPGRP0.PTC
# rm out.bin
rm $3#qr*
rm $5#qr*
