#!/bin/bash
set -e
ptctools="./../../python/ptctools/ptctools.py"

if [[ $# < 1 ]]; then
	echo "Usage: build ASMSOURCE PTCNAME"
	exit
fi

arm-none-eabi-as $1 -o out.elf
arm-none-eabi-objcopy -O binary out.elf out.bin

rm out.elf

if [[ $# < 2 ]]; then
	echo "Provide PTCNAME to continue"
	exit
fi

$ptctools encode launch.txt --name $2
$ptctools encode out.bin --format GRP --name TEMPGRP0

$ptctools pack $2.PTC -s 0x40000 --data-files TEMPGRP0.PTC
$ptctools qr $2.PTC --merge

open $2#merged.png

rm TEMPGRP0.PTC
# rm out.bin
rm $2#qr*
