#!/bin/bash
set -e

# check for PTCTOOLS
if [ -z ${PTCTOOLS:+x} ]
then
	echo "Set PTCTOOLS variable first!"
	echo "export PTCTOOLS=<path to ptctools.py>"
	exit
fi

# commmon loader
echo "Encoding common launcher _ASMLOAD"

$PTCTOOLS encode launch.txt --name _ASMLOAD
$PTCTOOLS qr _ASMLOAD.PTC --merge

if [[ $# < 1 ]]; then
	echo "Usage: build ASMSOURCE ASMGRP [program.txt]"
	exit
fi

# Actual ASM codes
echo "Assembling file"
arm-none-eabi-as $1 -o out.elf
arm-none-eabi-objcopy -O binary out.elf out.bin

rm out.elf

if [[ $# < 2 ]]; then
	echo "Provide GRP name to continue"
	exit
fi

# ASM data GRP
$PTCTOOLS encode out.bin --format GRP --name $2
$PTCTOOLS qr $2.PTC --merge

if [[ $# < 3 ]]; then
	echo "Provide program file to continue"
	exit
fi

# Extra program (useful to have here for testing)
$PTCTOOLS encode $3.txt
$PTCTOOLS qr $3.PTC --merge

rm out.bin
rm _ASMLOAD#qr*
rm $2#qr*
rm $3#qr*
